Aadarsh805/Unify

app/layout.tsx

tried putting dummy data on supabase and fetching realtime based on userids

chore: supabase realtime database changes fetching

---

app/components/SignupForm.tsx
app/layout.tsx
app/signup/page.tsx
server/signIn.ts
server/signup.ts

#31 need to solve this issue first before merging this

feat: signup/login functionlity on forms

---

app/account/layout.tsx
app/account/page.tsx
app/explore/[category]/page.tsx
app/explore/page.tsx

fix: decoration image in explore and category

---

.vscode/settings.json
app/components/LoginForm.tsx
app/components/SignupForm.tsx
app/layout.tsx
app/store/store.ts
server/signIn.ts
server/signup.ts
server/utils/getUserDetails.ts

chore: implemented auth stage functionality

---

app/store/store.ts
components/explore/ProductCard.tsx
server/deleteFromInterestedProducts.ts
server/insertToInterestedProducts.ts

feat: insert interested data to database

---

app/components/CreateProfile.tsx
app/components/Hero.tsx
app/components/HeroText.tsx
app/components/MysteryBox.tsx
app/components/Support.tsx
app/components/Tradition.tsx
app/page.tsx
public/assets/fonts/font.ts

- Added landing page
Closes #2

feat(landingpage): added landing page except footer

---

app/account/interested/page.tsx
app/account/layout.tsx
app/account/page.tsx
app/store/store.ts
components/wrappers/LayoutWrapper.tsx

Data fetch 1

---

app/account/page.tsx
app/layout.tsx
components/account/Modal.tsx

feat: Modal for Item upload

---

components/explore/ProductCard.tsx

Closes #55 
For some reason neither `stopPropagation` nor `StopimmediatePropagation` works so i just added a wrapper around it

fix: stop propagration

---

app/components/ProductCards.tsx
app/explore/[category]/page.tsx
app/explore/page.tsx
package.json
yarn.lock

feat: Product slider

---

app/[userProfile]/page.tsx
app/user/[userProfile]/layout.tsx
app/user/[userProfile]/page.tsx

feat(userprofile): user profile page added

---

app/components/ProductModalImage.tsx
components/account/Modal.tsx

- supabase bucket setup
- upload and download image from storage

feat: setup supabase bucket, uploading and downloading on add product modal

---

app/components/ProductModalImage.tsx
app/layout.tsx
app/store/store.ts
components/account/Modal.tsx
components/wrappers/LayoutWrapper.tsx

- modal image upload
- push products to table by userId

Supbase add products

---

components/account/Modal.tsx

fix: modal options

---

components/explore/Sidebar.tsx

merge after #65 
Closes #<issue_number>

Fix: sidebar link hover

---

components/account/Modal.tsx

fix: modal ui

---

components/wrappers/LayoutWrapper.tsx

- pushInterestedNotificatoin to the notifications table
- pushMatchNotification to notifications table
- pushMatches to math table

feat: realtime notificaion check and add to supabase

---

app/account/match/MatchCard.tsx
app/account/match/page.tsx
app/components/ProductCards.tsx
app/explore/[category]/[productId]/page.tsx
app/explore/page.tsx
app/store/store.ts
app/user/[userProfile]/layout.tsx
app/user/[userProfile]/page.tsx
components/explore/ProductCard.tsx
components/explore/Sidebar.tsx
components/wrappers/LayoutWrapper.tsx
next.config.js
server/deleteFromInterestedProducts.ts
server/insertToInterestedProducts.ts

Revert "Revert "feat: added match page and also updated explore page ui""

---

app/components/Navbar.tsx
app/components/NotificationIcon.tsx
app/components/NotificationMessage.tsx
app/components/ProductCards.tsx

Closes #78 
- Added the notification modal

feat: notification added

---

app/account/interested/page.tsx
app/account/match/page.tsx
app/account/page.tsx
app/components/NotificationIcon.tsx
app/store/store.ts
components/wrappers/LayoutWrapper.tsx

- account page products fetch
- interested page products fetch
- notifications fetch
- realtime notifications

Account data fetch

---

app/components/ProductCards.tsx
app/explore/[category]/page.tsx
app/user/[userProfile]/page.tsx
components/explore/Sidebar.tsx

fix: fixed code

---

app/explore/[category]/[productId]/page.tsx
app/explore/[category]/page.tsx
app/user/[userProfile]/page.tsx
components/explore/ProductCard.tsx
components/wrappers/LayoutWrapper.tsx
server/deleteFromInterestedProducts.ts
server/insertToInterestedProducts.ts

Interested product state are now on synchronization with database

feat: interested product management

---

app/components/Footer.tsx
app/components/Support.tsx
app/explore/[category]/[productId]/page.tsx

style: some minor ui changes

---

app/components/BackButton.tsx
app/components/ProductCards.tsx
app/explore/[category]/[productId]/page.tsx

feat: back button on details page

---

app/components/BackButton.tsx
app/components/ProductCards.tsx
app/explore/[category]/[productId]/page.tsx
app/user/[userProfile]/page.tsx
components/explore/ProductCard.tsx

feat: navigate to product page
